# Generated by Django 4.2.1 on 2023-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAsistenciaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('asunto', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
